// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as download$0 from "../internal/download/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as library$0 from "../internal/library/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sources$0 from "../internal/sources/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AttachTray wires the menu-bar tray from main.go.
 */
export function AttachTray(tray: application$0.SystemTray | null): $CancellablePromise<void> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.AttachTray", tray);
}

/**
 * BookBlurb returns the description for a library book: stored text first,
 * otherwise a one-time Open Library backfill that is then persisted.
 */
export function BookBlurb(id: number): $CancellablePromise<string> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.BookBlurb", id);
}

export function CancelTask(id: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.CancelTask", id);
}

export function CheckForUpdates(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.CheckForUpdates").then(($result: any) => {
        return $$createType1($result);
    });
}

export function ClearFinishedQueue(): $CancellablePromise<void> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.ClearFinishedQueue");
}

/**
 * CompleteWizard persists first-run choices and boots the stack end-to-end.
 */
export function CompleteWizard(libraryPath: string, launchAtLogin: boolean): $CancellablePromise<config$0.Settings | null> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.CompleteWizard", libraryPath, launchAtLogin).then(($result: any) => {
        return $$createType3($result);
    });
}

export function CountBooks(): $CancellablePromise<number> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.CountBooks");
}

/**
 * DeleteBook removes records and moves files to OS trash — never rm (§5.3).
 */
export function DeleteBook(id: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.DeleteBook", id);
}

/**
 * DeviceScan refreshes the connection and rebuilds the sync plan from the
 * library. Safe to call any time; cheap when the watcher already knows the
 * device is gone.
 */
export function DeviceScan(): $CancellablePromise<$models.DeviceState | null> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.DeviceScan").then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * DeviceStateSnapshot returns the last known state without touching the net.
 */
export function DeviceStateSnapshot(): $CancellablePromise<$models.DeviceState | null> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.DeviceStateSnapshot").then(($result: any) => {
        return $$createType5($result);
    });
}

export function Download(result: sources$0.Result, formatName: string): $CancellablePromise<download$0.Task | null> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.Download", result, formatName).then(($result: any) => {
        return $$createType7($result);
    });
}

export function Genres(): $CancellablePromise<string[]> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.Genres").then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetBook(id: number): $CancellablePromise<library$0.BookWithFiles | null> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.GetBook", id).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetProvisioningPreview returns the JSON that would land on the SD card.
 */
export function GetProvisioningPreview(): $CancellablePromise<string> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.GetProvisioningPreview");
}

export function GetQueue(): $CancellablePromise<download$0.Task[]> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.GetQueue").then(($result: any) => {
        return $$createType11($result);
    });
}

export function GetSettings(): $CancellablePromise<config$0.Settings | null> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.GetSettings").then(($result: any) => {
        return $$createType3($result);
    });
}

export function ImportFiles(): $CancellablePromise<void> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.ImportFiles");
}

export function ListByGenre(genre: string, sort: string, page: number): $CancellablePromise<library$0.BookWithFiles[]> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.ListByGenre", genre, sort, page).then(($result: any) => {
        return $$createType12($result);
    });
}

export function ListLibrary(query: string, sort: string, page: number): $CancellablePromise<library$0.BookWithFiles[]> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.ListLibrary", query, sort, page).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * OpenExternal hands a URL to the OS default browser. The webview blocks
 * target=_blank navigation, so every outbound link (Ko-fi, library file
 * downloads) routes through this binding instead.
 */
export function OpenExternal(rawURL: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.OpenExternal", rawURL);
}

/**
 * PickFolder opens the native directory chooser (wizard + settings).
 */
export function PickFolder(title: string): $CancellablePromise<string> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.PickFolder", title);
}

/**
 * ProbeFileSize HEADs a catalog download URL and returns its Content-Length
 * in bytes, for sources that don't advertise sizes in their search payload.
 * Cached per URL for the session.
 */
export function ProbeFileSize(rawURL: string): $CancellablePromise<number> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.ProbeFileSize", rawURL);
}

/**
 * ProvisionDeviceOPDS writes manicule's catalog into the reader's saved OPDS
 * server list over Wi-Fi — the SD-card drop, minus the SD card.
 */
export function ProvisionDeviceOPDS(): $CancellablePromise<void> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.ProvisionDeviceOPDS");
}

/**
 * RegeneratePin issues a fresh 4-digit PIN and applies it live.
 */
export function RegeneratePin(): $CancellablePromise<config$0.Settings | null> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.RegeneratePin").then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * RemoveFromDevice deletes files from the reader's SD card.
 */
export function RemoveFromDevice(paths: string[]): $CancellablePromise<$models.DeviceState | null> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.RemoveFromDevice", paths).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * RestartServer applies current settings to the running OPDS server.
 */
export function RestartServer(): $CancellablePromise<void> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.RestartServer");
}

/**
 * RevertClean deletes derived clean files; the master was always untouched.
 */
export function RevertClean(id: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.RevertClean", id);
}

/**
 * SaveProvisioningFile writes /.crosspoint/opds.json content anywhere the
 * user picks (their SD card), enabling the zero-typing device setup path.
 */
export function SaveProvisioningFile(): $CancellablePromise<string> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.SaveProvisioningFile");
}

/**
 * SaveSettings applies a partial update and persists it. Heavyweight side
 * effects (library move, server restart, watcher restart) happen here too so
 * the frontend never has to orchestrate them.
 */
export function SaveSettings(req: $models.SaveSettingsRequest): $CancellablePromise<config$0.Settings | null> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.SaveSettings", req).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SearchAll fans out to every enabled source in parallel and groups results
 * by source — no fake unified ranking (§2). Own-library hits come through
 * ListLibrary from the same UI bar.
 * 
 * Results stream to the frontend: a search:start event carries the per-source
 * skeletons the moment the fan-out begins, and each source emits search:group
 * as it finishes, so the UI paints the fastest catalog long before the slowest
 * one returns. The blocking return value stays the final, complete answer
 * (and serves repeat queries from a short-lived cache).
 */
export function SearchAll(query: string): $CancellablePromise<$models.SearchGroup[]> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.SearchAll", query).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * SendToDevice pushes one library book to the reader.
 */
export function SendToDevice(bookID: number): $CancellablePromise<$models.DeviceState | null> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.SendToDevice", bookID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ServerStatus(): $CancellablePromise<$models.ServerStatus> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.ServerStatus").then(($result: any) => {
        return $$createType15($result);
    });
}

export function SourceStatuses(): $CancellablePromise<{ [_ in string]?: any }[]> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.SourceStatuses").then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * SyncDevice sends every library book the reader is missing.
 */
export function SyncDevice(): $CancellablePromise<$models.DeviceState | null> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.SyncDevice").then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * TrayMenu builds the tray's context menu (called once from main).
 */
export function TrayMenu(): $CancellablePromise<application$0.Menu | null> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.TrayMenu").then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * WorkDescription returns a short blurb for a title/author pair, backfilled
 * from Open Library when the originating catalog didn't carry one.
 */
export function WorkDescription(title: string, authors: string[]): $CancellablePromise<string> {
    return $Call.ByName("github.com/doublezz10/manicule/app.Manicule.WorkDescription", title, authors);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = config$0.Settings.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.DeviceState.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = download$0.Task.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($Create.Any);
const $$createType9 = library$0.BookWithFiles.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $Create.Array($$createType6);
const $$createType12 = $Create.Array($$createType9);
const $$createType13 = $models.SearchGroup.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $models.ServerStatus.createFrom;
const $$createType16 = $Create.Map($Create.Any, $Create.Any);
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = application$0.Menu.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
