// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as device$0 from "../internal/device/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sources$0 from "../internal/sources/models.js";

/**
 * DeviceState is the Devices page model: connection phase plus the sync plan.
 */
export class DeviceState {
    /**
     * "searching" | "connected" | "offline"
     */
    "phase": string;
    "status"?: device$0.Status | null;
    "on_device": device$0.Match[];
    "missing": device$0.Match[];
    "orphan": device$0.DeviceFile[];
    "last_error"?: string;

    /** Creates a new DeviceState instance. */
    constructor($$source: Partial<DeviceState> = {}) {
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }
        if (!("on_device" in $$source)) {
            this["on_device"] = [];
        }
        if (!("missing" in $$source)) {
            this["missing"] = [];
        }
        if (!("orphan" in $$source)) {
            this["orphan"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceState instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceState {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField1_0($$parsedSource["status"]);
        }
        if ("on_device" in $$parsedSource) {
            $$parsedSource["on_device"] = $$createField2_0($$parsedSource["on_device"]);
        }
        if ("missing" in $$parsedSource) {
            $$parsedSource["missing"] = $$createField3_0($$parsedSource["missing"]);
        }
        if ("orphan" in $$parsedSource) {
            $$parsedSource["orphan"] = $$createField4_0($$parsedSource["orphan"]);
        }
        return new DeviceState($$parsedSource as Partial<DeviceState>);
    }
}

export class SaveSettingsRequest {
    "library_path"?: string | null;
    "sources_enabled"?: { [_ in string]?: boolean | null };
    "tier2_acknowledged"?: boolean | null;
    "source_credentials"?: { [_ in string]?: { [_ in string]?: string } };
    "clean_on_import"?: boolean | null;
    "image_max_width"?: number | null;
    "delete_source_after_import"?: boolean | null;
    "watch_enabled"?: boolean | null;
    "watch_path"?: string | null;
    "server_enabled"?: boolean | null;
    "server_port"?: number | null;
    "auth_enabled"?: boolean | null;
    "launch_at_login"?: boolean | null;
    "fleet_override_source"?: string | null;
    "fleet_override_url"?: string | null;
    "filing_mode"?: string | null;
    "default_source"?: string | null;
    "auto_send_device"?: boolean | null;

    /** Creates a new SaveSettingsRequest instance. */
    constructor($$source: Partial<SaveSettingsRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveSettingsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveSettingsRequest {
        const $$createField1_0 = $$createType6;
        const $$createField3_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sources_enabled" in $$parsedSource) {
            $$parsedSource["sources_enabled"] = $$createField1_0($$parsedSource["sources_enabled"]);
        }
        if ("source_credentials" in $$parsedSource) {
            $$parsedSource["source_credentials"] = $$createField3_0($$parsedSource["source_credentials"]);
        }
        return new SaveSettingsRequest($$parsedSource as Partial<SaveSettingsRequest>);
    }
}

export class SearchGroup {
    "source_id": string;
    "source_name": string;

    /**
     * ok | needs-auth | error | disabled
     */
    "state": string;
    "message"?: string;
    "results": sources$0.Result[];

    /** Creates a new SearchGroup instance. */
    constructor($$source: Partial<SearchGroup> = {}) {
        if (!("source_id" in $$source)) {
            this["source_id"] = "";
        }
        if (!("source_name" in $$source)) {
            this["source_name"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("results" in $$source)) {
            this["results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchGroup {
        const $$createField4_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField4_0($$parsedSource["results"]);
        }
        return new SearchGroup($$parsedSource as Partial<SearchGroup>);
    }
}

export class ServerStatus {
    "running": boolean;
    "port": number;

    /**
     * localhost form
     */
    "url": string;

    /**
     * for QR + device
     */
    "lan_url": string;
    "pin": string;
    "auth_enabled": boolean;
    "username": string;

    /** Creates a new ServerStatus instance. */
    constructor($$source: Partial<ServerStatus> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("lan_url" in $$source)) {
            this["lan_url"] = "";
        }
        if (!("pin" in $$source)) {
            this["pin"] = "";
        }
        if (!("auth_enabled" in $$source)) {
            this["auth_enabled"] = false;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerStatus($$parsedSource as Partial<ServerStatus>);
    }
}

/**
 * CheckForUpdates hits GitHub releases for a newer tag; v1 ships a manual
 * check link rather than auto-update (risk table §8).
 */
export class UpdateInfo {
    "current": string;
    "latest"?: string;
    "update": boolean;
    "url": string;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("current" in $$source)) {
            this["current"] = "";
        }
        if (!("update" in $$source)) {
            this["update"] = false;
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}

// Private type creation functions
const $$createType0 = device$0.Status.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = device$0.Match.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = device$0.DeviceFile.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
const $$createType8 = $Create.Map($Create.Any, $$createType7);
const $$createType9 = sources$0.Result.createFrom;
const $$createType10 = $Create.Array($$createType9);
