// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Settings is the full persisted application configuration.
 */
export class Settings {
    /**
     * LibraryPath is the root folder of the user's book library.
     */
    "library_path": string;

    /**
     * SourcesEnabled maps source ID → enabled. Tier 1 sources default on;
     * Tier 2 sources additionally require Tier2Acknowledged.
     */
    "sources_enabled": { [_ in string]?: boolean };
    "tier2_acknowledged": boolean;

    /**
     * SourceCredentials holds per-source credentials keyed by source ID.
     * Standard Ebooks uses {"email": "..."} (blank password per SE policy).
     */
    "source_credentials"?: { [_ in string]?: { [_ in string]?: string } };

    /**
     * auto-clean derivatives on import (default true)
     */
    "clean_on_import": boolean;

    /**
     * px cap for cleaned images (default 1440)
     */
    "image_max_width": number;

    /**
     * watch-folder remove toggle, default OFF
     */
    "delete_source_after_import": boolean;
    "watch_enabled": boolean;
    "watch_path"?: string;

    /**
     * OPDS server on while app runs
     */
    "server_enabled": boolean;

    /**
     * default 8787
     */
    "server_port": number;

    /**
     * ON by default with tiny creds
     */
    "auth_enabled": boolean;

    /**
     * 4-char numeric PIN, username fixed "reader"
     */
    "pin": string;
    "launch_at_login": boolean;

    /**
     * sourceID → manual endpoint base URL
     */
    "fleet_overrides"?: { [_ in string]?: string };

    /**
     * "author-title" (default), "genre-author-title", "decade-author-title"
     */
    "filing_mode"?: string;
    "wizard_done": boolean;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("library_path" in $$source)) {
            this["library_path"] = "";
        }
        if (!("sources_enabled" in $$source)) {
            this["sources_enabled"] = {};
        }
        if (!("tier2_acknowledged" in $$source)) {
            this["tier2_acknowledged"] = false;
        }
        if (!("clean_on_import" in $$source)) {
            this["clean_on_import"] = false;
        }
        if (!("image_max_width" in $$source)) {
            this["image_max_width"] = 0;
        }
        if (!("delete_source_after_import" in $$source)) {
            this["delete_source_after_import"] = false;
        }
        if (!("watch_enabled" in $$source)) {
            this["watch_enabled"] = false;
        }
        if (!("server_enabled" in $$source)) {
            this["server_enabled"] = false;
        }
        if (!("server_port" in $$source)) {
            this["server_port"] = 0;
        }
        if (!("auth_enabled" in $$source)) {
            this["auth_enabled"] = false;
        }
        if (!("pin" in $$source)) {
            this["pin"] = "";
        }
        if (!("launch_at_login" in $$source)) {
            this["launch_at_login"] = false;
        }
        if (!("wizard_done" in $$source)) {
            this["wizard_done"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField1_0 = $$createType0;
        const $$createField3_0 = $$createType2;
        const $$createField14_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sources_enabled" in $$parsedSource) {
            $$parsedSource["sources_enabled"] = $$createField1_0($$parsedSource["sources_enabled"]);
        }
        if ("source_credentials" in $$parsedSource) {
            $$parsedSource["source_credentials"] = $$createField3_0($$parsedSource["source_credentials"]);
        }
        if ("fleet_overrides" in $$parsedSource) {
            $$parsedSource["fleet_overrides"] = $$createField14_0($$parsedSource["fleet_overrides"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $Create.Map($Create.Any, $$createType1);
