// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DeviceFile is one e-book file found on the device.
 */
export class DeviceFile {
    "Path": string;
    "Size": number;

    /** Creates a new DeviceFile instance. */
    constructor($$source: Partial<DeviceFile> = {}) {
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Size" in $$source)) {
            this["Size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceFile instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceFile($$parsedSource as Partial<DeviceFile>);
    }
}

/**
 * Match pairs a library book with its device presence (DevicePath empty =
 * not on the device yet).
 */
export class Match {
    "book_id": number;
    "title": string;
    "author": string;
    "format": string;
    "device_path"?: string;
    "device_size"?: number;

    /**
     * where manicule files it on the device
     */
    "remote_path": string;

    /** Creates a new Match instance. */
    constructor($$source: Partial<Match> = {}) {
        if (!("book_id" in $$source)) {
            this["book_id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("remote_path" in $$source)) {
            this["remote_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Match instance from a string or object.
     */
    static createFrom($$source: any = {}): Match {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Match($$parsedSource as Partial<Match>);
    }
}

/**
 * Status mirrors GET /api/status.
 */
export class Status {
    "version": string;
    "ip": string;

    /**
     * "STA" (joined wifi) or "AP" (hotspot)
     */
    "mode": string;
    "rssi": number;
    "freeHeap": number;
    "uptime": number;

    /**
     * "X3" | "X4"
     */
    "device": string;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("rssi" in $$source)) {
            this["rssi"] = 0;
        }
        if (!("freeHeap" in $$source)) {
            this["freeHeap"] = 0;
        }
        if (!("uptime" in $$source)) {
            this["uptime"] = 0;
        }
        if (!("device" in $$source)) {
            this["device"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status($$parsedSource as Partial<Status>);
    }
}
