// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StateQueued = "queued",
    StateRunning = "running",
    StateDone = "done",
    StateFailed = "failed",
    StateDuplicate = "duplicate",
};

export class Task {
    "id": string;
    "source_id": string;
    "title": string;
    "authors": string[];
    "cover_url"?: string;
    "format_name": string;
    "state": State;
    "error"?: string;
    "book_id"?: number;
    "added_at": string;

    /** Creates a new Task instance. */
    constructor($$source: Partial<Task> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("source_id" in $$source)) {
            this["source_id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("authors" in $$source)) {
            this["authors"] = [];
        }
        if (!("format_name" in $$source)) {
            this["format_name"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = State.$zero;
        }
        if (!("added_at" in $$source)) {
            this["added_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     */
    static createFrom($$source: any = {}): Task {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("authors" in $$parsedSource) {
            $$parsedSource["authors"] = $$createField3_0($$parsedSource["authors"]);
        }
        return new Task($$parsedSource as Partial<Task>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
