// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Format is one downloadable rendition of a result.
 */
export class Format {
    /**
     * "EPUB", "MOBI", "XTCH", ...
     */
    "name": string;
    "url": string;

    /**
     * bytes, when known
     */
    "size"?: number;

    /** Creates a new Format instance. */
    constructor($$source: Partial<Format> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Format instance from a string or object.
     */
    static createFrom($$source: any = {}): Format {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Format($$parsedSource as Partial<Format>);
    }
}

/**
 * Result is one search hit. Grouped by SourceID in the UI — no fake unified ranking.
 */
export class Result {
    "source_id": string;
    "source_name": string;

    /**
     * source-specific stable id
     */
    "id": string;
    "title": string;
    "authors": string[];
    "language"?: string;
    "description"?: string;
    "subjects"?: string[];
    "cover_url"?: string;
    "year"?: string;
    "formats": Format[];

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("source_id" in $$source)) {
            this["source_id"] = "";
        }
        if (!("source_name" in $$source)) {
            this["source_name"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("authors" in $$source)) {
            this["authors"] = [];
        }
        if (!("formats" in $$source)) {
            this["formats"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        const $$createField4_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        const $$createField10_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("authors" in $$parsedSource) {
            $$parsedSource["authors"] = $$createField4_0($$parsedSource["authors"]);
        }
        if ("subjects" in $$parsedSource) {
            $$parsedSource["subjects"] = $$createField7_0($$parsedSource["subjects"]);
        }
        if ("formats" in $$parsedSource) {
            $$parsedSource["formats"] = $$createField10_0($$parsedSource["formats"]);
        }
        return new Result($$parsedSource as Partial<Result>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Format.createFrom;
const $$createType2 = $Create.Array($$createType1);
